stages:
  - test
 - scan

test_job:
  stage: test
  tags:
    - linux
  script:
    - rm -rf __pycache__
    - docker build -t local:test .
    - docker run -v ${PWD}:/opt/pwd local:test

scan_job:
  stage: scan
  tags:
    - linux
  image: sonarsource/sonar-scanner-cli
  variables:
    SONAR_TOKEN: sqp_b4a30f72a01b53da17b073fc8173515f56c57942
    SONAR_HOST_URL: https://sonarqube.ellisbs.co.uk
  script:
    - ~/sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner -Dsonar.projectKey=ctime   -Dsonar.sources=.   -Dsonar.host.url=${SONAR_HOST_URL}   -Dsonar.token=${SONAR_TOKEN}
