stages:
 - test
 - scan

test_job:
  stage: test
  image: docker:latest
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo apt-get install -y python3-dev python3-pip libasound2-dev
    - find / -name '*coverage*' 2>/dev/null
    - sh testscript.sh
  artifacts:
    paths:
      - coverage.xml
  variables:
    GIT_STRATEGY: clone

scan_job:
  stage: scan
  image: docker:latest
  tags:
    - linux
  script:
    - sh scan_job.sh
  dependencies:
    - test_job
  variables:
    GIT_STRATEGY: clone

