stages:
 - build
 - publish
 - test
 - scan

build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.whl

publish:
  stage: publish
  script:
    - pip install twine
    - twine upload --repository-url https://nexus.ellisbs.co.uk/repository/pypi-hosted/ --username $PYPI_USERNAME --password $PYPI_PASSWORD dist/*
  dependencies:
    - build

test_job:
  stage: test
  image: docker:latest
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo apt-get install -y python3-dev python3-pip libasound2-dev
    - sh testscript.sh
  artifacts:
    paths:
      - coverage.xml
  variables:
    GIT_STRATEGY: clone

scan_job:
  stage: scan
  image: docker:latest
  tags:
    - linux
  script:
    - sh scan_job.sh
  dependencies:
    - test_job
  variables:
    GIT_STRATEGY: clone

