stages:
 - build
 - publish
 - test
 - scan

build:
  stage: build
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo apt-get install -y python3-dev python3-pip libasound2-dev
    - python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*.tar.gz
      - dist/*.whl

publish:
  stage: publish
  tags:
    - linux
  script:
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo apt-get install -y python3-dev python3-pip libasound2-dev
    - pip install twine
    - ~/.local/bin/twine upload --repository-url https://nexus.ellisbs.co.uk/repository/pypi-hosted/ --username $PYPI_USERNAME --password $PYPI_PASSWORD dist/*
  dependencies:
    - build

test_job:
  stage: test
  tags:
    - linux
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo debconf-set-selections /path/to/keyboard-config.seed
    - sudo dpkg-reconfigure keyboard-configuration
    - sudo apt-get install -y python3-dev python3-pip libasound2-dev
    - sudo apt-get install -y xvfb xserver-xorg-video-dummy
    - sh testscript.sh
  artifacts:
    paths:
      - coverage.xml
  variables:
    GIT_STRATEGY: clone

scan_job:
  stage: scan
  tags:
    - linux
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - sudo apt-get update
    - sudo rm -rf /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock /var/cache/debconf/*.dat /var/cache/apt/archives/lock
    - sudo dpkg --configure -a
    - sudo apt-get install -f
    - sudo debconf-set-selections /path/to/keyboard-config.seed
    - sudo dpkg-reconfigure keyboard-configuration
    - sudo apt-get install -y unzip
    - sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
    - sudo unzip sonar-scanner-cli-4.8.0.2856-linux.zip
    - sudo mv sonar-scanner-4.8.0.2856-linux/ /opt/sonar-scanner
    - sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
    - sonar-scanner
  dependencies:
    - test_job
  variables:
    GIT_STRATEGY: clone

