stages:
 - test
 - scan

test_job:
  stage: test
  image: docker:latest
  tags:
    - linux
  script:
    - dnf update -y
    - dnf install -y python3-pip python3-devel
    - sh testscript.sh
  artifacts:
    paths:
      - coverage.xml
  variables:
    GIT_STRATEGY: clone

scan_job:
  stage: scan
  image: docker:latest
  tags:
    - linux
  script:
    - sh scan_job.sh
  dependencies:
    - test_job
  variables:
    GIT_STRATEGY: clone

